version: "3"
services:
  postgres:
    environment:
      POSTGRES_DB: recipesdb
      POSTGRES_PASSWORD: pass
    image: "postgres:12"
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data